### ISSUE TITLE
[1.18.2] Structures have lots of spawning issues and inconsistencies 

### ISSUE THREAD

**Issue by Razatop** [XxRexRaptorxX/Additional-Structures-Fabric#2]
Such as large flat overhangs where it needs a bigger flatter area, corners being empty from what I'm presuming being worldedit copies. Stuff like that, can catalogue with pictures if needed for specific ones. Other than that great mod :D

**Comment by XxRexRaptorxX** [comment]
Please send some images

**Comment by XxRexRaptorxX** [comment]
I don't use worldedit, the corners of many structures are filled with void blocks which are replaced with terrain blocks on generation. if there is no terrain that could cause the empty corners
