### ISSUE TITLE
Curseforge Third-party launcher downloads

### ISSUE THREAD

**Issue by DDriggs00** [XxRexRaptorxX/Additional-Structures-Fabric#3]
Would it be possible to allow using third-party launchers with this mod? it would make it much easier to use, especially by people unfamiliar with modded minecraft.

**Comment by DDriggs00** [comment]
Also, here's a more detailed appeal written by someone with a bit more experience than me: https://gist.github.com/copygirl/7d45bad739453d2be61138cebafce04c

**Comment by XxRexRaptorxX** [comment]
I'm still not quite sure, I shared my thoughts on the linked gist

**Comment by DDriggs00** [comment]
One more note, Many server hosting platforms (e.g. Aternos) are treated as third-party launchers when this setting is involved, preventing your mod from being used with them.

**Comment by XxRexRaptorxX** [comment]
3rd party distribution are now for all my mods allowed
