### ISSUE TITLE
Warning message in console on load - Not all defined tags for registry ResourceKey[minecraft:root / minecraft:worldgen/biome] are present in data pack: forge:is_savanna

### ISSUE THREAD

**Issue by SleepyCatten** [XxRexRaptorxX/Additional-Structures-Fabric#4]
Minecraft 1.19.2 with Fabric Loader 0.14.9

https://gist.github.com/SleepyCatten/ede1adf2ddb72e4696bd8b089bf17a12

"Not all defined tags for registry ResourceKey[minecraft:root / minecraft:worldgen/biome] are present in data pack: forge:is_savanna"

**Comment by XxRexRaptorxX** [comment]
Fixed in v.4.1.0

https://www.curseforge.com/minecraft/mc-mods/additional-structures-fabric/files/3941056
