### ISSUE TITLE
Scarecrows spawning at ridiculously high rates 

### ISSUE THREAD

**Issue by chorbintime** [XxRexRaptorxX/Additional-Structures-Fabric#6]
On the seed `5990050710196661415` at the coordinates -36 94 -3, there are [4 scarecrows in view](https://cdn.discordapp.com/attachments/1064320137735450694/1136144263466459186/2023-08-01_22.50.45.png). According to the mod's code, each scarecrow should generate 70 chunks apart.

This is replicable in many modpacks. The one I am testing in the screenshot is BMC2 Fabric. I have also seen reports of it happening on the Forge version of Additional Structures.

Latest Fabric Loader version, latest Additional Structures version

**Comment by XxRexRaptorxX** [comment]
MC version? Mod version?

**Comment by chorbintime** [comment]
1.20.1 fabric
AdditionalStructures-1.20.x-(v.4.2.0)

**Comment by chorbintime** [comment]
Happens on 1.20.1 Forge as well, modpack is BMC4 Forge
Seed is -5360922093071205614
![2023-08-05_04 16 38](https://github.com/XxRexRaptorxX/Additional-Structures-Fabric/assets/112908845/02e03cc1-bd30-4c03-b20f-80b62565e0f5)

**Comment by chorbintime** [comment]
Many apologies - this is actually the Explorations mod doing this. It spawns identical scarecrows that are marked as features instead of structures. 

Sorry for the bother!
